site_name: miKrate
site_url: https://fatory-org.gitlab.io/tools/mikrate/

repo_name: mikrate
repo_url: https://gitlab.com/factory-org/tools/mikrate
edit_uri: "-/edit/main/docs/src/docs"

theme:
  name: 'material'
  features:
    - navigation.tabs
  palette:
    scheme: slate
    primary: teal
    accent: orange
  icon:
    repo: fontawesome/brands/gitlab
  font:
    code: JetBrains Mono

nav:
  - Home: index.md
  - Guides:
      - guides/index.md
      - Simple:
          - Getting Started: guides/getting-started.md
          - R2DBC: guides/r2dbc.md
      - Frameworks:
          - Spring: guides/spring.md
  - API docs: /tools/mikrate/api/index.html

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - attr_list

plugins:
  - git-revision-date-localized
  - section-index
