image: azul/zulu-openjdk-alpine:11

include:
  - template: Dependency-Scanning.gitlab-ci.yml

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"
  DS_DEFAULT_ANALYZERS: "gemnasium-maven"

stages:
  - test
  - docs
  - deploy

test:
  stage: test
  interruptible: true
  dependencies: [ ]
  needs: [ ]
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull-push
    paths:
      - .gradle
  script:
    - ./gradlew build
  artifacts:
    reports:
      junit:
        - "*/build/test-results/test/**/TEST-*.xml"
        - "*/*/build/test-results/test/**/TEST-*.xml"

gemnasium-maven-dependency_scanning:
  allow_failure: false

pages:
  stage: docs
  dependencies: [ ]
  needs:
    - test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - .gradle
  script:
    - ./gradlew :dokkaHtmlMultiModule
    - mkdir public
    - mv build/dokka/htmlMultiModule public/api
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  dependencies: [ ]
  needs:
    - test
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - .gradle
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - ./gradlew publish
