image: azul/zulu-openjdk-alpine:17

include:
  - template: Dependency-Scanning.gitlab-ci.yml

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"
  DS_DEFAULT_ANALYZERS: "gemnasium-maven"

stages:
  - test
  - docs
  - deploy

test:
  stage: test
  interruptible: true
  services:
    - docker:20-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
  dependencies: [ ]
  needs: [ ]
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull-push
    paths:
      - .gradle
  script:
    - ./gradlew test jacocoTestReport
  artifacts:
    reports:
      junit:
        - "*/build/test-results/test/**/TEST-*.xml"
        - "*/*/build/test-results/test/**/TEST-*.xml"
      coverage_report:
        coverage_format: cobertura
        path: dsl/build/reports/jacoco/test/jacocoTestReport.cobertura.xml

gemnasium-maven-dependency_scanning:
  variables:
    SECURE_LOG_LEVEL: "debug"
  interruptible: true
  allow_failure: false

pages-test:
  image: registry.gitlab.com/factory-org/tools/docker/gradle-mkdocs
  stage: docs
  interruptible: true
  dependencies: [ ]
  needs: [ ]
  rules:
    - if: '$CI_COMMIT_TAG !~ /^v\d+\.\d+\.\d+$/ && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - .gradle
  script:
    - ./gradlew :dokkaHtmlMultiModule :docs:mkdocsBuild
    - test -d docs/build/mkdocs
    - test -d build/dokka/htmlMultiModule

pages-main:
  image: registry.gitlab.com/factory-org/tools/docker/gradle-mkdocs
  stage: docs
  interruptible: true
  dependencies: [ ]
  needs: [ ]
  rules:
    - if: '$CI_COMMIT_TAG !~ /^v\d+\.\d+\.\d+$/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - .gradle
  script:
    - ./gradlew :dokkaHtmlMultiModule :docs:mkdocsBuild
    - mv docs/build/mkdocs public
    - mv build/dokka/htmlMultiModule public/api
    - firebase deploy --only hosting:dev

pages:
  image: registry.gitlab.com/factory-org/tools/docker/gradle-mkdocs
  stage: docs
  interruptible: true
  dependencies: [ ]
  needs: [ ]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - .gradle
  script:
    - ./gradlew :dokkaHtmlMultiModule :docs:mkdocsBuild
    - mv docs/build/mkdocs public
    - mv build/dokka/htmlMultiModule public/api
    - firebase deploy --only hosting:stable

deploy:
  stage: deploy
  dependencies: [ ]
  needs:
    - gemnasium-maven-dependency_scanning
    - test
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - .gradle
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - ./gradlew publish

deploy-release:
  stage: deploy
  dependencies: [ ]
  needs:
    - test
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - .gradle
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
  script:
    - ./gradlew publish
