image: azul/zulu-openjdk-alpine:15

include:
  - template: Dependency-Scanning.gitlab-ci.yml

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"
  DS_DEFAULT_ANALYZERS: "gemnasium-maven"

stages:
  - test
  - deploy

test:
  stage: test
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull-push
    paths:
      - .gradle
      - build
      - core/build
      - dsl/build
  script:
    ./gradlew build

gemnasium-maven-dependency_scanning:
  allow_failure: false

deploy:
  stage: deploy
  dependencies: [ ]
  needs:
    - test
    - gemnasium-maven-dependency_scanning
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    policy: pull
    paths:
      - .gradle
      - build
      - core/build
      - dsl/build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    ./gradlew publish
